"""Initial migration

Revision ID: 158f6900310e
Revises: 
Create Date: 2026-07-07 08:46:54.360137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158f6900310e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_correo'), 'users', ['correo'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('legalizaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('destino_motivo', sa.String(length=255), nullable=False),
    sa.Column('anticipo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_gastado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legalizaciones_id'), 'legalizaciones', ['id'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legalizacion_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comprobante_url', sa.String(length=1000), nullable=True),
    sa.Column('sharepoint_item_id', sa.String(length=100), nullable=True),
    sa.Column('fecha_gasto', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legalizacion_id'], ['legalizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_legalizaciones_id'), table_name='legalizaciones')
    op.drop_table('legalizaciones')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_correo'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
